# Generated by Django 5.0.4 on 2024-04-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=123)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Constants',
            new_name='HomePage',
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': ''},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone3',
        ),
        migrations.AddField(
            model_name='contacts',
            name='phones',
            field=models.ManyToManyField(to='game.phone'),
        ),
    ]
