# Generated by Django 4.0.1 on 2024-04-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_ban',
            field=models.ImageField(default=1, upload_to='images/videos_ban/', verbose_name='Постер к видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='image_ban',
            field=models.ImageField(blank=True, null=True, upload_to='images/videos_ban/', verbose_name='Постер к видео'),
        ),
    ]
