# Generated by Django 5.0.4 on 2024-04-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AddField(
            model_name='game',
            name='image_bg',
            field=models.ImageField(default=1, upload_to='images/catalog_no_bg/'),
            preserve_default=False,
        ),
    ]
