# Generated by Django 5.0.4 on 2024-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_about_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_5',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_6',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='home_image_7',
        ),
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default=11, max_length=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=1, upload_to='images/review/%Y/%m/'),
            preserve_default=False,
        ),
    ]
