# Generated by Django 5.0.4 on 2024-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_homepage_home_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/review/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='files/reviews/'),
        ),
    ]
