# Generated by Django 5.0.4 on 2024-04-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_homepage_text_for_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_iframe',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
