# Generated by Django 5.0.4 on 2024-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_contacts_address_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Оригинальный текст, который отображается на сайте.', max_length=20000, verbose_name='Оригинальный текст')),
                ('current_text', models.TextField(help_text='Измененный или текущий текст, который отображается на сайте.', max_length=20000, verbose_name='Текущий текст')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
    ]
