# Generated by Django 5.0.4 on 2024-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_sitecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='title',
        ),
        migrations.AddField(
            model_name='contacts',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='Вк'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Ютуб'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='default_meta_description',
            field=models.TextField(default=1, help_text='Default meta description for SEO', max_length=20000, verbose_name='Default Meta Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='default_meta_keywords',
            field=models.CharField(default=1, help_text='Default meta keywords for SEO', max_length=255, verbose_name='Default Meta Keywords'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='favicon',
            field=models.FileField(blank=True, help_text='The favicon of the website', null=True, upload_to='favicons/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Footer Logo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.FileField(blank=True, help_text='The logo of the website', null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_name',
            field=models.CharField(default=1, help_text='The name of the website', max_length=255, verbose_name='Название сайта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='file',
            field=models.FileField(upload_to='files/about_us/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=234, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, default='Пусто', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='application',
            name='fullname',
            field=models.CharField(max_length=123, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=123, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(max_length=123, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_iframe',
            field=models.TextField(verbose_name='iframe'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address_link',
            field=models.URLField(verbose_name='Ссылка на адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Фейсбук'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Инстраграм'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phones',
            field=models.ManyToManyField(to='game.phone', verbose_name='Номера'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Телеграмм'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='whatsup',
            field=models.URLField(blank=True, null=True, verbose_name='Вотсап'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(upload_to='images/features/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='images/catalog/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_bg',
            field=models.ImageField(upload_to='images/catalog_no_bg/', verbose_name='Изображение на фон'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text_for_email',
            field=models.TextField(verbose_name='Описание для писем отправки'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/news/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=123, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/review/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='files/reviews/', verbose_name='Видео'),
        ),
    ]
