# Generated by Django 5.0.4 on 2024-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_homepage_title_contacts_vk_contacts_youtube_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_image',
            field=models.ImageField(default=1, upload_to='images/meta/'),
            preserve_default=False,
        ),
    ]
