# Generated by Django 5.0.4 on 2024-04-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image1',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image2',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image3',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image4',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image5',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image6',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image7',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='image8',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
    ]
