# Generated by Django 4.0.1 on 2024-04-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_homepage_image1_homepage_image2_homepage_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_ban',
            field=models.ImageField(default=1, upload_to='images/videos_ban/', verbose_name='Постер к видео'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='image_ban',
            field=models.ImageField(blank=True, null=True, upload_to='images/videos_ban/', verbose_name='Постер к видео'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phones',
            field=models.ManyToManyField(to='game.Phone', verbose_name='Номера'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_image',
            field=models.FileField(upload_to='images/meta/'),
        ),
    ]
